### ISSUE TITLE
ER schema is inconsistent with the relational schema (M)

### ISSUE THREAD

**Issue by smurthys** [DASSL/Gradebook#41]
The ER schema is quite inconsistent with the relational schema. It does not seem to have been updated as the relational schema changed.

**Comment by smurthys** [comment]
For starters, I recommend replacing the current schema with the schema from CS305-Alpha team's fork. It will help to discuss here the procedure of merging that team's changes here. 

I recommend discussing the actual changes to the schema in the PR rather than here so people can see the current and the proposed changes.

I also propose adding an image file **with the current schema** so it is easier to view.

**Comment by afig** [comment]
@jrm86 and I have determined the process of merging to involve the following steps: 

1. Remove anything specific to Team Alpha's additions (e.g. Significant Dates)
2. Consider what parts of the improved physical schema we want to keep (e.g. RBAC on tables and functions)
3. Check for any remaining spelling, grammar, or consistency issues (including copyright)

So far, we have mostly addressed steps 1 and 3 for the conceptual and logical schemas (progress is visible in the `fix_schema_inconsistencies` branch). We plan to address the remaining step 2 for the physical schema sometime tomorrow (1/16). As mentioned in the previous comment, specific changes will be discussed in the related PR. We will also add an image of the current schema before creating the PR.
