### ISSUE TITLE
importAttendance.psql fails for the first section whose attendance it imports

### ISSUE THREAD

**Issue by smurthys** [DASSL/Gradebook#58]
The function call `Gradebook.getSectionID(2017, 0, 'CS110', '05')` returns NULL because section number `05` does not exist: should be just `5`.

**Comment by afig** [comment]
A fix will be inplemented shortly, alongside the addition of a README section for the attendance data.

**Comment by afig** [comment]
Fixed in commit de1bbcd18470474943a137ede40312a3f4655750 (PR #60)
