### ISSUE TITLE
Importing Course Schedules seems to have added duplicate instructors (W)

### ISSUE THREAD

**Issue by smurthys** [DASSL/Gradebook#59]
After importing all sample OpenClose CSV files, instructor `Sean Murthy` appears four times in the `Instructor` table. FYI, I did import schedules out of sequence, but I don't imagine that causing duplicate instructors. 

For example, execute this query.
```sql
SELECT * FROM Gradebook.Instructor WHERE LName = 'Murthy'
```
Get this result (the different e-mail addresses are correct):

|id| fname | mname | lname |department|email|
| ------- | ----------- | ----------- | ----------- | ----------- | ----------- |
15324|Sean||Murthy||MurthyS@example.edu
15911|Sean||Murthy||MurthyS15911@example.edu
16659|Sean||Murthy||MurthyS16659@example.edu
17179|Sean||Murthy||MurthyS17179@example.edu

I have confirmed that `MName` has `NULL` in each of these result rows.

**Comment by srrollo** [comment]
The order definitely shouldn't matter.  Does your instructor table have the unique index added 3e0ffab317ccd475fbfc06403cba399d7ad84ea8?  This looks similar to the behavior I saw before adding it.  In the meantime I'll look over the script again.

**Comment by smurthys** [comment]
That is it. I do not have the second index on instructor names. BTW, only the first instance of the instructor is assigned to sections; the rest aren't used at all.

Thank you for checking this. I will close this issue.
